AllCops:
  TargetRubyVersion: 2.5.0

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true

Lint/EmptyBlock: # (new in 1.1)
  Enabled: true

Lint/EmptyClass: # (new in 1.3)
  Enabled: true

Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true

Lint/NestedMethodDefinition:
  Enabled: false

Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true

Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false
  EnforcedStyle: compact

Style/CollectionCompact: # (new in 1.2)
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true

Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: expanded

Style/Lambda:
  Enabled: true
  EnforcedStyle: literal

Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true

Style/NilLambda: # (new in 1.3)
  Enabled: true

Style/RedundantArgument: # (new in 1.4)
  Enabled: true

Style/SwapValues: # (new in 1.1)
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Metrics:
  Enabled: false
